export const HEALTH_CODES = {
  // Infrastructure Codes (Sprint 1)
  DB_CONNECTIVITY_FAILED: "DB_CONNECTIVITY_FAILED",
  DB_ACCESSIBILITY_FAILED: "DB_ACCESSIBILITY_FAILED",
  STORAGE_MISSING: "STORAGE_MISSING",
  STORAGE_UNREADABLE: "STORAGE_UNREADABLE",
  STORAGE_UNWRITABLE: "STORAGE_UNWRITABLE",
  STORAGE_CLEANUP_FAILED: "STORAGE_CLEANUP_FAILED",
  RUNTIME_CHECK_FAILED: "RUNTIME_CHECK_FAILED",

  // Configuration Codes (Sprint 2)
  CONFIG_ACADEMIC_YEAR_NOT_FOUND: "CONFIG_ACADEMIC_YEAR_NOT_FOUND",
  CONFIG_MULTIPLE_ACTIVE_ACADEMIC_YEARS: "CONFIG_MULTIPLE_ACTIVE_ACADEMIC_YEARS",
  CONFIG_SEMESTER_NOT_FOUND: "CONFIG_SEMESTER_NOT_FOUND",
  CONFIG_MULTIPLE_ACTIVE_SEMESTERS: "CONFIG_MULTIPLE_ACTIVE_SEMESTERS",
  CONFIG_SCHOOL_PROFILE_INCOMPLETE: "CONFIG_SCHOOL_PROFILE_INCOMPLETE",
  CONFIG_BRANDING_INCOMPLETE: "CONFIG_BRANDING_INCOMPLETE",
  CONFIG_STORAGE_NOT_CONFIGURED: "CONFIG_STORAGE_NOT_CONFIGURED",
  CONFIG_AUDIT_NOT_CONFIGURED: "CONFIG_AUDIT_NOT_CONFIGURED",
  CONFIG_ENV_MISSING: "CONFIG_ENV_MISSING",

  // Operational Service Codes (Sprint 3)
  AUDIT_SERVICE_UNAVAILABLE: "AUDIT_SERVICE_UNAVAILABLE",
  JOB_QUEUE_WORKER_UNVERIFIED: "JOB_QUEUE_WORKER_UNVERIFIED",
  BACKGROUND_WORKER_NOT_FOUND: "BACKGROUND_WORKER_NOT_FOUND",
  CACHE_SERVICE_UNAVAILABLE: "CACHE_SERVICE_UNAVAILABLE",
  BACKUP_SERVICE_NOT_IMPLEMENTED: "BACKUP_SERVICE_NOT_IMPLEMENTED",
  DIAGNOSTICS_ENDPOINT_UNAVAILABLE: "DIAGNOSTICS_ENDPOINT_UNAVAILABLE",

  // Business Data Integrity Codes (Sprint 4)

  // -- Academic Year Integrity
  INTEGRITY_ACADEMIC_YEAR_NO_ACTIVE: "INTEGRITY_ACADEMIC_YEAR_NO_ACTIVE",
  INTEGRITY_ACADEMIC_YEAR_MULTIPLE_ACTIVE:
    "INTEGRITY_ACADEMIC_YEAR_MULTIPLE_ACTIVE",
  INTEGRITY_ACADEMIC_YEAR_NO_SEMESTERS: "INTEGRITY_ACADEMIC_YEAR_NO_SEMESTERS",
  INTEGRITY_SEMESTER_ACTIVE_IN_INACTIVE_YEAR:
    "INTEGRITY_SEMESTER_ACTIVE_IN_INACTIVE_YEAR",

  // -- Semester Integrity
  INTEGRITY_SEMESTER_NO_ACTIVE: "INTEGRITY_SEMESTER_NO_ACTIVE",
  INTEGRITY_SEMESTER_MULTIPLE_ACTIVE: "INTEGRITY_SEMESTER_MULTIPLE_ACTIVE",
  INTEGRITY_SEMESTER_YEAR_MISMATCH: "INTEGRITY_SEMESTER_YEAR_MISMATCH",

  // -- Enrollment Integrity
  INTEGRITY_ENROLLMENT_STUDENT_UNENROLLED:
    "INTEGRITY_ENROLLMENT_STUDENT_UNENROLLED",
  INTEGRITY_ENROLLMENT_ORPHANED_STUDENT: "INTEGRITY_ENROLLMENT_ORPHANED_STUDENT",
  INTEGRITY_ENROLLMENT_ORPHANED_CLASS: "INTEGRITY_ENROLLMENT_ORPHANED_CLASS",

  // -- Assessment Integrity
  INTEGRITY_ASSESSMENT_INVALID_SCORE_RANGE:
    "INTEGRITY_ASSESSMENT_INVALID_SCORE_RANGE",
  INTEGRITY_ASSESSMENT_ORPHANED_TEACHER: "INTEGRITY_ASSESSMENT_ORPHANED_TEACHER",
  INTEGRITY_ASSESSMENT_ORPHANED_SUBJECT: "INTEGRITY_ASSESSMENT_ORPHANED_SUBJECT",

  // -- Score Integrity
  INTEGRITY_SCORE_OUT_OF_RANGE: "INTEGRITY_SCORE_OUT_OF_RANGE",
  INTEGRITY_SCORE_ORPHANED_STUDENT: "INTEGRITY_SCORE_ORPHANED_STUDENT",
  INTEGRITY_SCORE_ORPHANED_ENROLLMENT: "INTEGRITY_SCORE_ORPHANED_ENROLLMENT",

  // -- Attendance Integrity
  INTEGRITY_ATTENDANCE_ORPHANED_TEACHER: "INTEGRITY_ATTENDANCE_ORPHANED_TEACHER",
  INTEGRITY_ATTENDANCE_FUTURE_DATE: "INTEGRITY_ATTENDANCE_FUTURE_DATE",

  // -- Finance Integrity
  INTEGRITY_FINANCE_OVERPAYMENT: "INTEGRITY_FINANCE_OVERPAYMENT",
  INTEGRITY_FINANCE_PAID_ZERO_AMOUNT: "INTEGRITY_FINANCE_PAID_ZERO_AMOUNT",
  INTEGRITY_FINANCE_ORPHANED_STUDENT: "INTEGRITY_FINANCE_ORPHANED_STUDENT",

  // -- Audit Log Integrity
  INTEGRITY_AUDIT_MISSING_ACTION: "INTEGRITY_AUDIT_MISSING_ACTION",
  INTEGRITY_AUDIT_MISSING_ENTITY_TYPE: "INTEGRITY_AUDIT_MISSING_ENTITY_TYPE",

  // -- Dashboard Dependency Integrity
  INTEGRITY_DASHBOARD_NO_ACTIVE_CLASS: "INTEGRITY_DASHBOARD_NO_ACTIVE_CLASS",
  INTEGRITY_DASHBOARD_NO_ACTIVE_SUBJECT: "INTEGRITY_DASHBOARD_NO_ACTIVE_SUBJECT",
  INTEGRITY_DASHBOARD_NO_ACTIVE_STAFF: "INTEGRITY_DASHBOARD_NO_ACTIVE_STAFF",

  // Section Execution
  CHECKER_EXECUTION_FAILED: "CHECKER_EXECUTION_FAILED",
} as const;

export type HealthCode = keyof typeof HEALTH_CODES;
