import { AppError } from "@/lib/errors";
import { getGeminiConfig, AIGenerationSource, AIFallbackReason } from "@/lib/config/gemini";
import { checkAIUsageLimit, recordAIUsageAttempt, classifyProvider429, AIUsageSnapshot } from "@/lib/services/aiUsageGuard";
import {
  RPMActivityItem,
  RPMActivityInput,
  RPMRubrikItem,
  RPMKegiatanMetadata,
  VALID_TRISULA,
  VALID_FITRAH,
  VALID_SAHABAT,
  VALID_UTSMAN,
  VALID_KURNAS,
  DplKurnasValue,
  normalizeActivityItem,
  formatActivityItemWithTags,
} from "@/lib/utils/rpmUtils";
import { isUuid } from "@/lib/utils/academicUtils";

export type { RPMActivityItem, RPMActivityInput, DplKurnasValue, RPMRubrikItem, RPMKegiatanMetadata };
export { normalizeActivityItem, formatActivityItemWithTags, VALID_KURNAS, VALID_TRISULA, VALID_FITRAH, VALID_SAHABAT, VALID_UTSMAN };

export type RPMGenerateTarget =
  | "ALL"
  | "PEMAHAMAN_BERMAKNA"
  | "PERTANYAAN_PEMANTIK"
  | "MEDIA_AJAR"
  | "SUMBER_BELAJAR"
  | "PESAN_ORANG_TUA";

export interface RPMGenerateParams {
  mataPelajaran: string;
  kelasRombel: string;
  tingkatFase: string;
  alokasiWaktu: number; // in minutes
  modulTopik: string;
  userId?: string;
  // Authoritative context — passed in, NOT generated by AI
  semester?: string;       // e.g. "Ganjil"
  academicYear?: string;   // e.g. "2026/2027"
  capaianPembelajaran?: string;  // existing CP if already selected
  tujuanPembelajaran?: string[]; // existing TP list if already selected
  karakterFitrah?: string[];     // selected character values (for rubric generation)
  target?: RPMGenerateTarget;    // default: "ALL"
}

export interface RPMContent {
  identitas: {
    mataPelajaran: string;
    kelasRombel: string;
    tingkatFase: string;
    /** Human-readable snapshot for print. Source = master semester, NOT AI-generated. */
    semesterTahun?: string;
    /** Actual semester ID from master data */
    semesterId?: string;
    /** Academic year string snapshot */
    tahunAjaran?: string;
    alokasiWaktu: number;
    modulTopik: string;
    trisulaKompetensi: string[];
    deskripsiTrisula: { literasi: string; numerasi: string; diniyyah: string };
    karakterFitrah: string[];
    budayaSahabat: string[];
    dplUtsman: string[];
    dplKurnas: string[];
    namaTutorPengampu?: string;
  };
  desainPembelajaran: {
    capaianPembelajaran: string;
    pemahamanBermakna: string;
    tujuanPembelajaran: string[];
    /** Open-ended questions to stimulate curiosity — 2-3 items */
    pertanyaanPemantik?: string[];
    /** Concrete teaching media/tools — 3-5 items */
    mediaAjar?: string[];
    /** Realistic learning sources — 3-5 items */
    sumberBelajar?: string[];
    kegiatanPembelajaran: {
      awal: RPMActivityInput[];
      inti: RPMActivityInput[];
      akhir: RPMActivityInput[];
      /** Optional structured metadata for each phase */
      metadata?: RPMKegiatanMetadata;
    };
    asesmen: {
      awal: string;
      formatif: string;
      sumatif: string;
      pesanEdukasiOrangTua: string;
      /** Character observation rubric derived from selected karakterFitrah */
      rubrikKarakterFitrah?: RPMRubrikItem[];
    };
  };
}

export interface RPMGenerationResult {
  source: AIGenerationSource;
  content: RPMContent;
  target?: RPMGenerateTarget;
  data?: string | string[];
  fallbackReason?: AIFallbackReason;
  usage?: AIUsageSnapshot;
}


export function getFallbackLocalRPMTemplate(
  params: RPMGenerateParams,
  reason: AIFallbackReason = 'NO_API_KEY',
  usage?: AIUsageSnapshot
): RPMGenerationResult {
  const intiTime = Math.max(params.alokasiWaktu - 20, 20);
  const awalTime = 10;
  const akhirTime = 10;
  const resolvedIntiTime = params.alokasiWaktu - awalTime - akhirTime;

  // Build rubric from karakterFitrah if provided
  const rubrikRows: RPMRubrikItem[] = (params.karakterFitrah || ["Keimanan", "Kemandirian", "Adab & Akhlak", "Kreativitas"]).map((k) => ({
    indikator: k,
    sangatBaik: `Santri secara konsisten menunjukkan sikap ${k.toLowerCase()} yang nyata dalam setiap kegiatan pembelajaran, baik secara mandiri maupun bersama kelompok.`,
    perluBimbingan: `Santri belum menunjukkan sikap ${k.toLowerCase()} secara konsisten dan masih memerlukan dorongan serta bimbingan dari tutor.`,
  }));

  const safeSemester = params.semester && !isUuid(params.semester) ? params.semester : undefined;
  const safeAcademicYear = params.academicYear && !isUuid(params.academicYear) ? params.academicYear : "";

  const fullContent: RPMContent = {
    identitas: {
        mataPelajaran: params.mataPelajaran,
        kelasRombel: params.kelasRombel,
        tingkatFase: params.tingkatFase,
        semesterTahun: safeSemester ? `Semester ${safeSemester}` : "Semester Ganjil",
        tahunAjaran: safeAcademicYear,
        alokasiWaktu: params.alokasiWaktu,
        modulTopik: params.modulTopik,
        trisulaKompetensi: ["Literasi", "Numerasi", "Diniyyah"],
        deskripsiTrisula: {
          literasi: `Melalui topik ${params.modulTopik}, santri diajak membaca, menganalisis, dan memetakan informasi kontekstual dari teks referensi untuk memperluas cakrawala pemahaman materi secara kritis dan komunikatif.`,
          numerasi: `Kegiatan pemelajaran ${params.modulTopik} mengintegrasikan penalaran logis, penghitungan kuantitatif, serta logika pemecahan masalah angka untuk memperkuat keterampilan matematis praktis santri.`,
          diniyyah: `Setiap tahapan pemelajaran ${params.modulTopik} dihubungkan dengan dalil Al-Qur'an/Hadits, penanaman adab menuntut ilmu, serta pembentukan akhlak karimah dalam pengaplikasian ilmu sehari-hari.`,
        },
        karakterFitrah: params.karakterFitrah || ["Keimanan", "Kemandirian", "Adab & Akhlak", "Kreativitas"],
        budayaSahabat: ["Disiplin", "Jujur", "Empati", "Tanggung Jawab"],
        dplUtsman: ["Keberanian", "Kedermawanan", "Kejujuran"],
        dplKurnas: ["Penalaran Kritis", "Kemandirian", "Kreativitas", "Kolaborasi"],
      },
      desainPembelajaran: {
        capaianPembelajaran: params.capaianPembelajaran || `Santri memahami dan menguasai konsep dasar ${params.modulTopik} secara mendalam serta mampu menerapkannya dalam memecahkan masalah kontekstual.`,
        pemahamanBermakna: `Santri menyadari pentingnya ${params.modulTopik} dalam kehidupan sehari-hari sebagai sarana meningkatkan kebermanfaatan diri dan ketaatan kepada Allah SWT.`,
        tujuanPembelajaran: params.tujuanPembelajaran && params.tujuanPembelajaran.length > 0
          ? params.tujuanPembelajaran
          : [
              `Mengidentifikasi dan menjelaskan konsep dasar ${params.modulTopik} dengan tepat.`,
              `Melakukan latihan terbimbing dan pemecahan masalah mengenai ${params.modulTopik}.`,
              `Merefleksikan hikmah pembelajaran dan menerapkan adab Islami dalam setiap proses belajar.`,
            ],
        pertanyaanPemantik: [
          `Apa yang sudah kamu ketahui tentang ${params.modulTopik}?`,
          `Mengapa ${params.modulTopik} penting untuk dipelajari dalam kehidupan sehari-hari?`,
          `Bagaimana cara kamu memecahkan masalah yang berkaitan dengan ${params.modulTopik}?`,
        ],
        mediaAjar: [
          `Modul/LKPD ${params.modulTopik}`,
          "Papan tulis dan spidol warna",
          "Kartu konsep (flashcard)",
          "Buku teks mata pelajaran",
          "Alat peraga sederhana sesuai topik",
        ],
        sumberBelajar: [
          `Modul ajar ${params.mataPelajaran} ${params.tingkatFase}`,
          "Buku paket siswa",
          "Lingkungan sekitar sebagai sumber belajar kontekstual",
          "Materi digital dari sumber terpercaya",
          "Pengalaman belajar sehari-hari santri",
        ],
        kegiatanPembelajaran: {
          awal: [
            {
              teks: `Pembukaan, pembacaan doa belajar, dan apersepsi kontekstual mengenai materi ${params.modulTopik}`,
              tagBudaya: ["Disiplin"],
              tagKarakter: ["Adab & Akhlak", "Keimanan"],
            },
          ],
          inti: [
            {
              teks: `Eksplorasi materi dasar ${params.modulTopik}, diskusi kelompok, dan pembacaan teks modul terbimbing`,
              tagBudaya: ["Empati", "Jujur"],
              tagKarakter: ["Kemandirian", "Penalaran Kritis"],
            },
            {
              teks: `Praktik latihan soal/pemecahan masalah ${params.modulTopik} dan presentasi hasil kerja kelompok`,
              tagBudaya: ["Tanggung Jawab"],
              tagKarakter: ["Keberanian", "Kreativitas"],
            },
          ],
          akhir: [
            {
              teks: `Refleksi bersama mengenai materi ${params.modulTopik}, penyimpulan hikmah pembelajaran, dan doa penutup`,
              tagBudaya: ["Jujur"],
              tagKarakter: ["Adab & Akhlak", "Keimanan"],
            },
          ],
          metadata: {
            awal: {
              fokus: "Pembukaan dan apersepsi kontekstual",
              durasiMenit: awalTime,
              fokusAdab: "Adab berdoa dan menghormati guru",
            },
            inti: {
              fokus: "Eksplorasi materi, diskusi, dan latihan",
              durasiMenit: Math.max(resolvedIntiTime, awalTime),
              pendekatanMetode: "Pembelajaran kooperatif dan kontekstual",
            },
            akhir: {
              fokus: "Refleksi dan penutupan",
              durasiMenit: akhirTime,
              fokusRefleksi: "Hikmah pembelajaran dan adab penutup majlis ilmu",
            },
          },
        },
        asesmen: {
          awal: `Tanya jawab lisan diagnostik untuk mengukur pemahaman awal santri terkait ${params.modulTopik}.`,
          formatif: `Observasi sikap, kemandirian, dan ketelitian santri selama pengerjaan tugas & diskusi kelompok materi ${params.modulTopik}.`,
          sumatif: `Evaluasi tertulis & unjuk kerja penyelesaian masalah kontekstual ${params.modulTopik} di akhir topik.`,
          pesanEdukasiOrangTua: `Mohon orang tua mendampingi ananda di rumah dalam mengulas kembali materi ${params.modulTopik} serta membiasakan sikap disiplin dan adab positif.`,
          rubrikKarakterFitrah: rubrikRows,
        },
      },
    };

  let selectiveData: string | string[] | undefined = undefined;
  if (params.target === 'PEMAHAMAN_BERMAKNA') {
    selectiveData = fullContent.desainPembelajaran.pemahamanBermakna;
  } else if (params.target === 'PERTANYAAN_PEMANTIK') {
    selectiveData = fullContent.desainPembelajaran.pertanyaanPemantik;
  } else if (params.target === 'MEDIA_AJAR') {
    selectiveData = fullContent.desainPembelajaran.mediaAjar;
  } else if (params.target === 'SUMBER_BELAJAR') {
    selectiveData = fullContent.desainPembelajaran.sumberBelajar;
  } else if (params.target === 'PESAN_ORANG_TUA') {
    selectiveData = fullContent.desainPembelajaran.asesmen.pesanEdukasiOrangTua;
  }

  return {
    source: 'FALLBACK',
    target: params.target || 'ALL',
    data: selectiveData,
    content: fullContent,
    fallbackReason: reason,
    usage,
  };
}

export async function generateSelectiveRPMFieldWithAI(
  params: RPMGenerateParams
): Promise<RPMGenerationResult> {
  const { apiKey, model, endpointUrl } = getGeminiConfig();

  if (!apiKey || !endpointUrl) {
    return getFallbackLocalRPMTemplate(params, 'NO_API_KEY');
  }

  // 1. Guard check local AI usage limits
  const usageCheck = await checkAIUsageLimit(model);
  if (!usageCheck.allowed && usageCheck.blockedReason) {
    await recordAIUsageAttempt({
      userId: params.userId,
      feature: 'RPM_GENERATOR',
      model,
      source: 'FALLBACK',
      providerErrorReason: usageCheck.blockedReason,
      retryAttempt: 1,
    });
    return getFallbackLocalRPMTemplate(params, usageCheck.blockedReason, usageCheck.snapshot);
  }

  const target = params.target || 'ALL';
  const tpContext = (params.tujuanPembelajaran || []).filter(Boolean).slice(0, 3).join('; ') || '-';
  const cpContext = params.capaianPembelajaran ? params.capaianPembelajaran.substring(0, 200) : '-';
  const karakterContext = (params.karakterFitrah || ["Keimanan", "Kemandirian", "Adab & Akhlak", "Kreativitas"]).join(', ');

  let prompt = '';
  if (target === 'PEMAHAMAN_BERMAKNA') {
    prompt = `
Anda adalah pakar kurikulum dan pedagogi Islam terpadu (SIUBA / Kurikulum Merdeka).
Tugas Anda: Buatlah TEPAT 1 PARAGRAF RINGKAS DAN KONTEKSTUAL (±2–4 kalimat) mengenai "Pemahaman Bermakna (Deep Insight)" untuk rancangan pemelajaran berikut:
- Mata Pelajaran: ${params.mataPelajaran}
- Fase / Kelas: ${params.tingkatFase} (${params.kelasRombel})
- Topik / Modul: ${params.modulTopik}
- Capaian Pembelajaran (CP): ${cpContext}
- Tujuan Pembelajaran (TP): ${tpContext}
- Karakter FITRAH: ${karakterContext}

PANDUAN PEDAGOGIS:
1. Jelaskan pemahaman esensial apa yang akan melekat pada sanubari santri dalam jangka panjang setelah mempelajari topik ini.
2. Jelaskan mengapa hal ini penting dan bagaimana korelasinya dengan kehidupan nyata serta ketaatan beribadah / akhlak.
3. Hindari kalimat klise atau sekadar mengulang definisi materi.
4. Format output JSON murni tanpa markdown:
{
  "pemahamanBermakna": "Satu paragraf utuh (2-4 kalimat) pemahaman bermakna mendalam..."
}
    `.trim();
  } else if (target === 'PERTANYAAN_PEMANTIK') {
    prompt = `
Anda adalah pakar kurikulum dan pedagogi Islam terpadu (SIUBA / Kurikulum Merdeka).
Tugas Anda: Buatlah TEPAT 2–3 "Pertanyaan Pemantik (Curiosity Triggers)" untuk memantik rasa ingin tahu santri pada topik berikut:
- Mata Pelajaran: ${params.mataPelajaran}
- Fase / Kelas: ${params.tingkatFase} (${params.kelasRombel})
- Topik / Modul: ${params.modulTopik}
- Tujuan Pembelajaran (TP): ${tpContext}

PANDUAN PEDAGOGIS:
1. Tepat 2–3 pertanyaan terbuka (open-ended).
2. Sesuai usia anak fase ${params.tingkatFase}.
3. Memantik rasa ingin tahu dan penalaran kritis.
4. BUKAN pertanyaan tes/kuis fakta (bukan: "Apa pengertian dari...", "Sebutkan 3 jenis...").
5. Format output JSON murni tanpa markdown:
{
  "pertanyaanPemantik": [
    "Pertanyaan terbuka 1?",
    "Pertanyaan terbuka 2?",
    "Pertanyaan terbuka 3?"
  ]
}
    `.trim();
  } else if (target === 'MEDIA_AJAR') {
    prompt = `
Anda adalah pakar kurikulum dan sarana pembelajaran praktis (SIUBA / Kurikulum Merdeka).
Tugas Anda: Buatlah 3–5 rekomendasi "Media Ajar / Sarana" yang konkret, berbiaya rendah, dan realistis di sekolah/madrasah untuk topik berikut:
- Mata Pelajaran: ${params.mataPelajaran}
- Fase / Kelas: ${params.tingkatFase} (${params.kelasRombel})
- Topik / Modul: ${params.modulTopik}

PANDUAN PEDAGOGIS:
1. Rekomendasikan 3–5 media konkret & praktis (contoh: LKPD eksplorasi kontekstual, flashcard/kartu konsep, diagram/infografis visual, benda/alat peraga sederhana sekitar kelas, media digital interaktif sederhana).
2. Jangan merekomendasikan alat mahal/mewah yang tidak realistis.
3. Format output JSON murni tanpa markdown:
{
  "mediaAjar": [
    "Media 1",
    "Media 2",
    "Media 3",
    "Media 4"
  ]
}
    `.trim();
  } else if (target === 'SUMBER_BELAJAR') {
    prompt = `
Anda adalah pakar kurikulum dan rujukan belajar (SIUBA / Kurikulum Merdeka).
Tugas Anda: Buatlah 3–5 "Sumber Belajar / Rujukan" yang realistis dan kredibel untuk topik berikut:
- Mata Pelajaran: ${params.mataPelajaran}
- Fase / Kelas: ${params.tingkatFase} (${params.kelasRombel})
- Topik / Modul: ${params.modulTopik}

PANDUAN PEDAGOGIS:
1. Rekomendasikan 3–5 sumber belajar yang nyata (misal: Buku Teks Mata Pelajaran ${params.mataPelajaran} Fase ${params.tingkatFase}, Modul Ajar Tematik SIUBA, Lingkungan sekitar dan observasi langsung, Referensi digital terpercaya, Dalil Al-Qur'an/Hadits yang relevan jika sesuai konteks).
2. JANGAN mengarang judul buku fiktif beserta nama pengarang atau tautan URL palsu.
3. Format output JSON murni tanpa markdown:
{
  "sumberBelajar": [
    "Sumber 1",
    "Sumber 2",
    "Sumber 3",
    "Sumber 4"
  ]
}
    `.trim();
  } else if (target === 'PESAN_ORANG_TUA') {
    prompt = `
Anda adalah pakar parenting Islami dan kemitraan madrasatul ula (sekolah & orang tua).
Tugas Anda: Buatlah TEPAT 1 PARAGRAF "Pesan Edukasi Orang Tua (Madrasatul Ula)" untuk mendampingi santri di rumah pada materi berikut:
- Mata Pelajaran: ${params.mataPelajaran}
- Fase / Kelas: ${params.tingkatFase} (${params.kelasRombel})
- Topik / Modul: ${params.modulTopik}
- Tujuan Pembelajaran (TP): ${tpContext}
- Nilai Karakter FITRAH: ${karakterContext}

PANDUAN PEDAGOGIS:
1. Paragraf komunikatif, hangat, dan solutif bagi orang tua (±2–4 kalimat).
2. Berikan aksi sederhana yang dapat dilakukan orang tua di rumah untuk memperkuat materi dan pembiasaan adab baik.
3. Hindari bahasa yang menggurui atau terlalu teoritis.
4. Format output JSON murni tanpa markdown:
{
  "pesanEdukasiOrangTua": "Satu paragraf panduan pendampingan orang tua di rumah..."
}
    `.trim();
  } else {
    return getFallbackLocalRPMTemplate(params, 'UNKNOWN');
  }

  const maxRetries = 2;
  let attempt = 0;
  let lastFallbackReason: AIFallbackReason = 'UNKNOWN';

  while (attempt < maxRetries) {
    attempt++;
    const reqStartedAt = new Date();
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 25000);

    try {
      const response = await fetch(endpointUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        signal: controller.signal,
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
        }),
      });

      clearTimeout(timeoutId);
      const durationMs = Date.now() - reqStartedAt.getTime();

      if (response.status === 429) {
        const rawErrText = await response.text().catch(() => '');
        const classified = classifyProvider429(response.status, rawErrText);
        lastFallbackReason = classified;

        await recordAIUsageAttempt({
          userId: params.userId,
          feature: 'RPM_GENERATOR',
          model,
          source: 'FALLBACK',
          providerHttpStatus: 429,
          providerErrorReason: classified,
          durationMs,
          retryAttempt: attempt,
          requestStartedAt: reqStartedAt,
        });

        if (classified === 'DAILY_QUOTA') {
          return getFallbackLocalRPMTemplate(params, 'DAILY_QUOTA', usageCheck.snapshot);
        }

        if (attempt < maxRetries) {
          const backoffDelay = Math.pow(2, attempt) * 1000 + Math.random() * 500;
          await new Promise((resolve) => setTimeout(resolve, backoffDelay));
          continue;
        }

        return getFallbackLocalRPMTemplate(params, 'RATE_LIMIT', usageCheck.snapshot);
      }

      if (response.status >= 500 || !response.ok) {
        lastFallbackReason = 'HTTP_ERROR';
        await recordAIUsageAttempt({
          userId: params.userId,
          feature: 'RPM_GENERATOR',
          model,
          source: 'FALLBACK',
          providerHttpStatus: response.status,
          providerErrorReason: 'HTTP_ERROR',
          durationMs,
          retryAttempt: attempt,
          requestStartedAt: reqStartedAt,
        });

        if (attempt < maxRetries) {
          const backoffDelay = Math.pow(2, attempt) * 1000;
          await new Promise((resolve) => setTimeout(resolve, backoffDelay));
          continue;
        }
        return getFallbackLocalRPMTemplate(params, 'HTTP_ERROR', usageCheck.snapshot);
      }

      const data = await response.json();
      const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text || "";
      const cleanedText = rawText.replace(/```json/gi, "").replace(/```/g, "").trim();
      let parsed: any;

      try {
        parsed = JSON.parse(cleanedText);
      } catch {
        await recordAIUsageAttempt({
          userId: params.userId,
          feature: 'RPM_GENERATOR',
          model,
          source: 'FALLBACK',
          providerHttpStatus: 200,
          providerErrorReason: 'INVALID_JSON',
          durationMs,
          retryAttempt: attempt,
          requestStartedAt: reqStartedAt,
        });
        return getFallbackLocalRPMTemplate(params, 'INVALID_JSON', usageCheck.snapshot);
      }

      let extractedData: string | string[] | undefined;
      const fallbackResult = getFallbackLocalRPMTemplate(params, 'UNKNOWN', usageCheck.snapshot);
      const resultingContent = fallbackResult.content;

      if (target === 'PEMAHAMAN_BERMAKNA') {
        const text = typeof parsed.pemahamanBermakna === 'string' ? parsed.pemahamanBermakna.trim() : undefined;
        if (!text) throw new Error("Missing pemahamanBermakna");
        extractedData = text;
        resultingContent.desainPembelajaran.pemahamanBermakna = text;
      } else if (target === 'PERTANYAAN_PEMANTIK') {
        const list = Array.isArray(parsed.pertanyaanPemantik)
          ? parsed.pertanyaanPemantik.filter((p: any) => typeof p === 'string' && p.trim().length > 0)
          : [];
        if (list.length === 0) throw new Error("Missing pertanyaanPemantik");
        extractedData = list;
        resultingContent.desainPembelajaran.pertanyaanPemantik = list;
      } else if (target === 'MEDIA_AJAR') {
        const list = Array.isArray(parsed.mediaAjar)
          ? parsed.mediaAjar.filter((m: any) => typeof m === 'string' && m.trim().length > 0)
          : [];
        if (list.length === 0) throw new Error("Missing mediaAjar");
        extractedData = list;
        resultingContent.desainPembelajaran.mediaAjar = list;
      } else if (target === 'SUMBER_BELAJAR') {
        const list = Array.isArray(parsed.sumberBelajar)
          ? parsed.sumberBelajar.filter((s: any) => typeof s === 'string' && s.trim().length > 0)
          : [];
        if (list.length === 0) throw new Error("Missing sumberBelajar");
        extractedData = list;
        resultingContent.desainPembelajaran.sumberBelajar = list;
      } else if (target === 'PESAN_ORANG_TUA') {
        const text = typeof parsed.pesanEdukasiOrangTua === 'string'
          ? parsed.pesanEdukasiOrangTua.trim()
          : typeof parsed.pesanOrangTua === 'string'
          ? parsed.pesanOrangTua.trim()
          : undefined;
        if (!text) throw new Error("Missing pesanEdukasiOrangTua");
        extractedData = text;
        resultingContent.desainPembelajaran.asesmen.pesanEdukasiOrangTua = text;
      }

      await recordAIUsageAttempt({
        userId: params.userId,
        feature: 'RPM_GENERATOR',
        model,
        source: 'GEMINI',
        providerHttpStatus: 200,
        durationMs,
        retryAttempt: attempt,
        requestStartedAt: reqStartedAt,
      });

      return {
        source: 'GEMINI',
        target,
        data: extractedData,
        content: resultingContent,
        usage: usageCheck.snapshot,
      };
    } catch (err: any) {
      clearTimeout(timeoutId);
      lastFallbackReason = controller.signal.aborted ? 'TIMEOUT' : 'NETWORK_ERROR';
      const durationMs = Date.now() - reqStartedAt.getTime();

      await recordAIUsageAttempt({
        userId: params.userId,
        feature: 'RPM_GENERATOR',
        model,
        source: 'FALLBACK',
        providerErrorReason: lastFallbackReason,
        durationMs,
        retryAttempt: attempt,
        requestStartedAt: reqStartedAt,
      });

      if (attempt >= maxRetries) {
        return getFallbackLocalRPMTemplate(params, lastFallbackReason, usageCheck.snapshot);
      }
      const backoffDelay = Math.pow(2, attempt) * 1000;
      await new Promise((resolve) => setTimeout(resolve, backoffDelay));
    }
  }

  return getFallbackLocalRPMTemplate(params, lastFallbackReason, usageCheck.snapshot);
}

export async function generateRPMContentWithAI(params: RPMGenerateParams): Promise<RPMGenerationResult> {
  if (params.target && params.target !== 'ALL') {
    return generateSelectiveRPMFieldWithAI(params);
  }

  const { apiKey, model, endpointUrl } = getGeminiConfig();

  if (!apiKey || !endpointUrl) {
    return getFallbackLocalRPMTemplate(params, 'NO_API_KEY');
  }

  // 1. Guard check local RPM & RPD limits
  const usageCheck = await checkAIUsageLimit(model);
  if (!usageCheck.allowed && usageCheck.blockedReason) {
    await recordAIUsageAttempt({
      userId: params.userId,
      feature: 'RPM_GENERATOR',
      model,
      source: 'FALLBACK',
      providerErrorReason: usageCheck.blockedReason,
      retryAttempt: 1,
    });
    return getFallbackLocalRPMTemplate(params, usageCheck.blockedReason, usageCheck.snapshot);
  }

  const awalTime = 10;
  const akhirTime = 10;
  const resolvedIntiTime = Math.max(params.alokasiWaktu - awalTime - akhirTime, 10);

  // Build rubric character list for AI context
  const karakterForRubric = params.karakterFitrah && params.karakterFitrah.length > 0
    ? params.karakterFitrah
    : ["Keimanan", "Kemandirian", "Adab & Akhlak", "Kreativitas"];

  const safeSemester = params.semester && !isUuid(params.semester) ? params.semester : undefined;
  const safeAcademicYear = params.academicYear && !isUuid(params.academicYear) ? params.academicYear : undefined;

  const contextInfo = [
    safeSemester ? `- Semester: ${safeSemester}` : '',
    safeAcademicYear ? `- Tahun Ajaran: ${safeAcademicYear}` : '',
    params.capaianPembelajaran ? `- CP yang sudah dipilih: ${params.capaianPembelajaran.substring(0, 200)}` : '',
    params.tujuanPembelajaran && params.tujuanPembelajaran.length > 0
      ? `- TP yang sudah ada: ${params.tujuanPembelajaran.slice(0, 3).join('; ')}` : '',
  ].filter(Boolean).join('\n');

  const prompt = `
Anda adalah pakar penyusun Rencana Pemelajaran (RPM) Kurikulum SIUBA / Kurikulum Merdeka Terpadu.
Buatkan rancangan RPM terstruktur dalam format JSON murni tanpa markdown wrapper untuk data berikut:
- Mata Pelajaran: ${params.mataPelajaran}
- Kelas / Rombel: ${params.kelasRombel}
- Tingkat / Fase: ${params.tingkatFase}
- Alokasi Waktu: ${params.alokasiWaktu} Menit (Awal: ${awalTime} + Inti: ${resolvedIntiTime} + Penutup: ${akhirTime})
- Topik / Modul: ${params.modulTopik}
${contextInfo ? `\nKONTEKS RESMI (JANGAN DIUBAH AI):\n${contextInfo}` : ''}

ATURAN PENTING & DETAILED REQUIREMENTS (WAJIB DIPATUHI SANGAT KETAT):
1. trisulaKompetensi: SELALU sertakan ketiga pilar baku: ${JSON.stringify(VALID_TRISULA)}
2. deskripsiTrisula: Tulis penjelasan lengkap 1 PARAGRAF UTUH untuk masing-masing pilar ("literasi", "numerasi", "diniyyah"). Penjelasan harus mengintegrasikan topik "${params.modulTopik}" secara mendalam, ilmiah, dan bernilai Diniyyah/Islamiah (bukan cuma 1 kalimat pendek).
3. karakterFitrah: Pilih 4-5 nilai (generous) yang PALING relevan untuk topik ini dari: ${JSON.stringify(VALID_FITRAH)}
4. budayaSahabat: Pilih 4-5 nilai (generous) yang PALING relevan untuk topik ini dari: ${JSON.stringify(VALID_SAHABAT)}
5. dplUtsman: Pilih 3-5 nilai (generous) yang PALING relevan untuk topik ini dari: ${JSON.stringify(VALID_UTSMAN)}
6. dplKurnas: Pilih 4-5 nilai (generous) dari DAFTAR BAKU INI (JANGAN MENGARANG NILAI BARU): ${JSON.stringify(VALID_KURNAS)}
7. kegiatanPembelajaran: Terdiri dari objek "awal", "inti", "akhir". Setiap item HARUS BERUPA OBJECT:
   { "teks": "Deskripsi rinci langkah aktivitas", "tagBudaya": ["Nama Tag"], "tagKarakter": ["Nama Tag"] }
   - "tagBudaya": 1-2 tag relevan dari daftar budayaSahabat
   - "tagKarakter": 1-2 tag relevan dari daftar karakterFitrah/dplUtsman/dplKurnas
8. kegiatanPembelajaran.metadata: Isi durasi terstruktur TEPAT:
   - awal.durasiMenit: ${awalTime}
   - inti.durasiMenit: ${resolvedIntiTime}
   - akhir.durasiMenit: ${akhirTime}
   - Total HARUS = ${params.alokasiWaktu} menit
9. pertanyaanPemantik: Buat TEPAT 2-3 pertanyaan terbuka (open-ended) yang:
   - Merangsang rasa ingin tahu
   - Sesuai usia/fase siswa
   - Terhubung dengan topik
   - BUKAN pertanyaan ujian (bukan: "Apa itu X?")
   - Boleh terhubung dengan nilai FITRAH/Islam secara alami, JANGAN dipaksakan di setiap pertanyaan
10. mediaAjar: Buat 3-5 rekomendasi media/sarana pembelajaran yang:
    - Konkret dan praktis untuk lingkungan sekolah/pesantren
    - Sesuai dengan mapel "${params.mataPelajaran}", fase "${params.tingkatFase}", topik "${params.modulTopik}"
    - JANGAN rekomendasikan alat mahal atau tidak realistis
    - Contoh: LKPD, flashcard, model visual, alat percobaan sederhana, gambar/poster, peta konsep
11. sumberBelajar: Buat 3-5 sumber belajar realistis:
    - Preferensikan sumber yang tersedia: modul sekolah, buku paket, lingkungan sekitar, observasi
    - Al-Qur'an/Hadits HANYA jika relevan dengan konteks mata pelajaran
    - JANGAN mengarang judul buku spesifik dengan edisi/penulis jika tidak ada dalam konteks
    - Nama generik lebih aman: "Buku teks mapel", "Modul SIUBA", dll.
12. asesmen: Buat kriteria SPESIFIK ke topik "${params.modulTopik}" (BUKAN generik)
13. rubrikKarakterFitrah: Buat baris rubrik untuk SETIAP karakter dalam daftar ini: ${JSON.stringify(karakterForRubric)}
    - Setiap baris: { "indikator": "<nama karakter>", "sangatBaik": "<deskriptor perilaku konkret>", "perluBimbingan": "<deskriptor perilaku konkret>" }
    - Deskriptor HARUS berupa perilaku OBSERVABLE (dapat diamati), bukan abstrak
    - CONTOH BAIK: "Menyelesaikan tugas mandiri dengan teliti dan bertanggung jawab"
    - CONTOH BURUK: "Memiliki jiwa yang luar biasa"

Kembalikan respon DALAM FORMAT JSON PRESIS DENGAN STRUKTUR BERIKUT:
{
  "identitas": {
    "mataPelajaran": "${params.mataPelajaran}",
    "kelasRombel": "${params.kelasRombel}",
    "tingkatFase": "${params.tingkatFase}",
    "alokasiWaktu": ${params.alokasiWaktu},
    "modulTopik": "${params.modulTopik}",
    "trisulaKompetensi": ["Literasi", "Numerasi", "Diniyyah"],
    "deskripsiTrisula": {
      "literasi": "Paragraf lengkap...",
      "numerasi": "Paragraf lengkap...",
      "diniyyah": "Paragraf lengkap..."
    },
    "karakterFitrah": ["...", "..."],
    "budayaSahabat": ["...", "..."],
    "dplUtsman": ["...", "..."],
    "dplKurnas": ["...", "..."]
  },
  "desainPembelajaran": {
    "capaianPembelajaran": "...",
    "pemahamanBermakna": "...",
    "tujuanPembelajaran": ["...", "...", "..."],
    "pertanyaanPemantik": ["Pertanyaan 1?", "Pertanyaan 2?", "Pertanyaan 3?"],
    "mediaAjar": ["Media 1", "Media 2", "Media 3", "Media 4", "Media 5"],
    "sumberBelajar": ["Sumber 1", "Sumber 2", "Sumber 3", "Sumber 4"],
    "kegiatanPembelajaran": {
      "awal": [{ "teks": "...", "tagBudaya": ["Disiplin"], "tagKarakter": ["Adab & Akhlak"] }],
      "inti": [
        { "teks": "...", "tagBudaya": ["Jujur"], "tagKarakter": ["Kemandirian"] },
        { "teks": "...", "tagBudaya": ["Tanggung Jawab"], "tagKarakter": ["Kreativitas"] }
      ],
      "akhir": [{ "teks": "...", "tagBudaya": ["Jujur"], "tagKarakter": ["Adab & Akhlak"] }],
      "metadata": {
        "awal": { "fokus": "Pembukaan dan apersepsi", "durasiMenit": ${awalTime}, "fokusAdab": "Adab berdoa dan menghormati guru" },
        "inti": { "fokus": "Eksplorasi dan latihan", "durasiMenit": ${resolvedIntiTime}, "pendekatanMetode": "Pembelajaran kooperatif kontekstual" },
        "akhir": { "fokus": "Refleksi dan penutupan", "durasiMenit": ${akhirTime}, "fokusRefleksi": "Hikmah pembelajaran dan adab penutup" }
      }
    },
    "asesmen": {
      "awal": "...",
      "formatif": "...",
      "sumatif": "...",
      "pesanEdukasiOrangTua": "...",
      "rubrikKarakterFitrah": [
        { "indikator": "${karakterForRubric[0] || 'Keimanan'}", "sangatBaik": "...", "perluBimbingan": "..." }
      ]
    }
  }
}
  `.trim();

  const maxRetries = 2;
  let attempt = 0;
  let lastFallbackReason: AIFallbackReason = 'UNKNOWN';

  while (attempt < maxRetries) {
    attempt++;
    const reqStartedAt = new Date();
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 30000);

    try {
      const response = await fetch(endpointUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        signal: controller.signal,
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
        }),
      });

      clearTimeout(timeoutId);
      const durationMs = Date.now() - reqStartedAt.getTime();

      if (response.status === 429) {
        const rawErrText = await response.text().catch(() => '');
        const classified = classifyProvider429(response.status, rawErrText);
        lastFallbackReason = classified;

        await recordAIUsageAttempt({
          userId: params.userId,
          feature: 'RPM_GENERATOR',
          model,
          source: 'FALLBACK',
          providerHttpStatus: 429,
          providerErrorReason: classified,
          durationMs,
          retryAttempt: attempt,
          requestStartedAt: reqStartedAt,
        });

        if (classified === 'DAILY_QUOTA') {
          return getFallbackLocalRPMTemplate(params, 'DAILY_QUOTA', usageCheck.snapshot);
        }

        if (attempt < maxRetries) {
          const backoffDelay = Math.pow(2, attempt) * 1000 + Math.random() * 500;
          await new Promise((resolve) => setTimeout(resolve, backoffDelay));
          continue;
        }

        return getFallbackLocalRPMTemplate(params, 'RATE_LIMIT', usageCheck.snapshot);
      }

      if (response.status >= 500) {
        lastFallbackReason = 'HTTP_ERROR';
        await recordAIUsageAttempt({
          userId: params.userId,
          feature: 'RPM_GENERATOR',
          model,
          source: 'FALLBACK',
          providerHttpStatus: response.status,
          providerErrorReason: 'HTTP_ERROR',
          durationMs,
          retryAttempt: attempt,
          requestStartedAt: reqStartedAt,
        });

        if (attempt < maxRetries) {
          const backoffDelay = Math.pow(2, attempt) * 1000;
          await new Promise((resolve) => setTimeout(resolve, backoffDelay));
          continue;
        }
        return getFallbackLocalRPMTemplate(params, 'HTTP_ERROR', usageCheck.snapshot);
      }

      if (!response.ok) {
        await recordAIUsageAttempt({
          userId: params.userId,
          feature: 'RPM_GENERATOR',
          model,
          source: 'FALLBACK',
          providerHttpStatus: response.status,
          providerErrorReason: 'HTTP_ERROR',
          durationMs,
          retryAttempt: attempt,
          requestStartedAt: reqStartedAt,
        });
        return getFallbackLocalRPMTemplate(params, 'HTTP_ERROR', usageCheck.snapshot);
      }

      const data = await response.json();
      const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text || "";
      const cleanedText = rawText.replace(/```json/gi, "").replace(/```/g, "").trim();
      let parsed: RPMContent;

      try {
        parsed = JSON.parse(cleanedText);
      } catch {
        await recordAIUsageAttempt({
          userId: params.userId,
          feature: 'RPM_GENERATOR',
          model,
          source: 'FALLBACK',
          providerHttpStatus: 200,
          providerErrorReason: 'INVALID_JSON',
          durationMs,
          retryAttempt: attempt,
          requestStartedAt: reqStartedAt,
        });
        return getFallbackLocalRPMTemplate(params, 'INVALID_JSON', usageCheck.snapshot);
      }

      if (!parsed.identitas || !parsed.desainPembelajaran) {
        await recordAIUsageAttempt({
          userId: params.userId,
          feature: 'RPM_GENERATOR',
          model,
          source: 'FALLBACK',
          providerHttpStatus: 200,
          providerErrorReason: 'INVALID_SCHEMA',
          durationMs,
          retryAttempt: attempt,
          requestStartedAt: reqStartedAt,
        });
        return getFallbackLocalRPMTemplate(params, 'INVALID_SCHEMA', usageCheck.snapshot);
      }

      // Sanitize dplKurnas
      if (Array.isArray(parsed.identitas?.dplKurnas)) {
        parsed.identitas.dplKurnas = parsed.identitas.dplKurnas.filter(
          (v: string) => (VALID_KURNAS as readonly string[]).includes(v)
        );
        if (parsed.identitas.dplKurnas.length === 0) {
          parsed.identitas.dplKurnas = ["Penalaran Kritis", "Kemandirian"];
        }
      }

      // Ensure trisulaKompetensi has all three pillars
      if (!parsed.identitas.trisulaKompetensi || parsed.identitas.trisulaKompetensi.length === 0) {
        parsed.identitas.trisulaKompetensi = ["Literasi", "Numerasi", "Diniyyah"];
      }

      // Guard: Ensure AI output does not overwrite or leak UUIDs into identity period snapshots
      if (isUuid(parsed.identitas?.tahunAjaran)) {
        parsed.identitas.tahunAjaran = safeAcademicYear || "";
      }
      if (isUuid(parsed.identitas?.semesterTahun)) {
        parsed.identitas.semesterTahun = safeSemester ? `Semester ${safeSemester}` : "";
      }

      // Guard: AI must not override authoritative context fields
      if (params.capaianPembelajaran) {
        parsed.desainPembelajaran.capaianPembelajaran = params.capaianPembelajaran;
      }
      if (params.tujuanPembelajaran && params.tujuanPembelajaran.length > 0) {
        parsed.desainPembelajaran.tujuanPembelajaran = params.tujuanPembelajaran;
      }

      // Sanitize rubrik: ensure it corresponds to selected karakterFitrah
      const expectedKarakter = new Set(karakterForRubric);
      const existingRubrik = Array.isArray(parsed.desainPembelajaran?.asesmen?.rubrikKarakterFitrah)
        ? parsed.desainPembelajaran.asesmen.rubrikKarakterFitrah
        : [];
      const existingMap = new Map(existingRubrik.map((r: RPMRubrikItem) => [r.indikator, r]));

      const sanitizedRubrik: RPMRubrikItem[] = karakterForRubric.map((k) => {
        if (existingMap.has(k)) return existingMap.get(k)!;
        return {
          indikator: k,
          sangatBaik: `Santri menunjukkan sikap ${k.toLowerCase()} secara konsisten dan mandiri dalam kegiatan pembelajaran.`,
          perluBimbingan: `Santri belum menunjukkan sikap ${k.toLowerCase()} secara konsisten dan memerlukan bimbingan lanjutan.`,
        };
      });

      if (parsed.desainPembelajaran?.asesmen) {
        parsed.desainPembelajaran.asesmen.rubrikKarakterFitrah = sanitizedRubrik;
      }

      // Ensure arrays for new fields
      if (!Array.isArray(parsed.desainPembelajaran?.pertanyaanPemantik)) {
        parsed.desainPembelajaran.pertanyaanPemantik = [];
      }
      if (!Array.isArray(parsed.desainPembelajaran?.mediaAjar)) {
        parsed.desainPembelajaran.mediaAjar = [];
      }
      if (!Array.isArray(parsed.desainPembelajaran?.sumberBelajar)) {
        parsed.desainPembelajaran.sumberBelajar = [];
      }

      // Record successful GEMINI attempt
      await recordAIUsageAttempt({
        userId: params.userId,
        feature: 'RPM_GENERATOR',
        model,
        source: 'GEMINI',
        providerHttpStatus: 200,
        durationMs,
        retryAttempt: attempt,
        requestStartedAt: reqStartedAt,
      });

      return {
        source: 'GEMINI',
        content: parsed,
        usage: usageCheck.snapshot,
      };
    } catch (err: any) {
      clearTimeout(timeoutId);
      lastFallbackReason = controller.signal.aborted ? 'TIMEOUT' : 'NETWORK_ERROR';
      const durationMs = Date.now() - reqStartedAt.getTime();

      await recordAIUsageAttempt({
        userId: params.userId,
        feature: 'RPM_GENERATOR',
        model,
        source: 'FALLBACK',
        providerErrorReason: lastFallbackReason,
        durationMs,
        retryAttempt: attempt,
        requestStartedAt: reqStartedAt,
      });

      if (attempt >= maxRetries) {
        return getFallbackLocalRPMTemplate(params, lastFallbackReason, usageCheck.snapshot);
      }
      const backoffDelay = Math.pow(2, attempt) * 1000;
      await new Promise((resolve) => setTimeout(resolve, backoffDelay));
    }
  }

  return getFallbackLocalRPMTemplate(params, lastFallbackReason, usageCheck.snapshot);
}

// ═════════════════════════════════════════════════════════════════════════════
// RINCIAN PARAGRAF TRISULA KOMPETENSI (1 PARAGRAF PER PILAR)
// ═════════════════════════════════════════════════════════════════════════════

export interface TrisulaParagraphGenerateParams {
  mataPelajaran: string;
  tingkatFase?: string;
  kelasRombel?: string;
  modulTopik: string;
  tujuanPembelajaran?: string[];
  kegiatanPembelajaran?: {
    awal?: Array<{ teks: string }>;
    inti?: Array<{ teks: string }>;
    akhir?: Array<{ teks: string }>;
  };
  alokasiWaktu?: number;
  userId?: string;
}

export interface TrisulaParagraphsData {
  literasi: string;
  numerasi: string;
  diniyyah: string;
}

export interface TrisulaParagraphResult {
  source: AIGenerationSource;
  data: TrisulaParagraphsData;
  fallbackReason?: AIFallbackReason;
  usage?: AIUsageSnapshot;
}

export function getFallbackTrisulaParagraphs(
  params: TrisulaParagraphGenerateParams,
  reason: AIFallbackReason = 'NO_API_KEY',
  usage?: AIUsageSnapshot
): TrisulaParagraphResult {
  const mapelLower = (params.mataPelajaran || '').toLowerCase();
  const isKuantitatif =
    mapelLower.includes('matematika') ||
    mapelLower.includes('fisika') ||
    mapelLower.includes('kimia') ||
    mapelLower.includes('ipa') ||
    mapelLower.includes('ekonomi') ||
    mapelLower.includes('akuntansi');

  const validTPs = (params.tujuanPembelajaran || []).filter((t) => t && t.trim().length > 0);
  const tpContext = validTPs.length > 0
    ? ` dengan fokus capaian pada ${validTPs[0].replace(/\.$/, '')}`
    : '';

  const numerasiText = isKuantitatif
    ? `Dalam kegiatan pembelajaran ${params.modulTopik}, santri diajak melakukan penalaran matematis terstruktur dengan mengumpulkan data observasi, menghitung variabel terkait, dan menganalisis hubungan kuantitatif secara sistematis.`
    : `Kegiatan pemelajaran ${params.modulTopik} mengintegrasikan penalaran logis kontekstual, di mana santri mengelompokkan fakta, membandingkan pola informasi, serta menyajikan urutan data sederhana dalam bentuk tabel perbandingan yang mudah dipahami.`;

  return {
    source: 'FALLBACK',
    fallbackReason: reason,
    usage,
    data: {
      literasi: `Melalui topik ${params.modulTopik}${tpContext}, santri membaca dan menelaah materi sumber secara saksama, mengidentifikasi istilah-istilah kunci, serta mengomunikasikan pemahaman gagasannya secara tertulis maupun lisan dengan bahasa yang lugas.`,
      numerasi: numerasiText,
      diniyyah: `Selama proses pembelajaran ${params.modulTopik}, santri membiasakan adab menuntut ilmu dengan saling menghargai pendapat dalam diskusi, menjaga kejujuran serta ketelitian kerja, dan merefleksikan keteraturan ilmu sebagai tanda kebesaran Allah SWT.`,
    },
  };
}

export async function generateTrisulaParagraphsWithAI(
  params: TrisulaParagraphGenerateParams
): Promise<TrisulaParagraphResult> {
  const { apiKey, model, endpointUrl } = getGeminiConfig();

  if (!apiKey || !endpointUrl) {
    return getFallbackTrisulaParagraphs(params, 'NO_API_KEY');
  }

  // Check AI Usage Guard
  const usageCheck = await checkAIUsageLimit(model);
  if (!usageCheck.allowed && usageCheck.blockedReason) {
    await recordAIUsageAttempt({
      userId: params.userId,
      feature: 'RPM_TRISULA',
      model,
      source: 'FALLBACK',
      providerErrorReason: usageCheck.blockedReason,
      retryAttempt: 1,
    });
    return getFallbackTrisulaParagraphs(params, usageCheck.blockedReason, usageCheck.snapshot);
  }

  const tpListStr = (params.tujuanPembelajaran || [])
    .filter((t) => t && t.trim().length > 0)
    .map((t, i) => `${i + 1}. ${t}`)
    .join('\n') || '-';

  const kegiatanStr = [
    ...(params.kegiatanPembelajaran?.awal || []).map((k) => k.teks),
    ...(params.kegiatanPembelajaran?.inti || []).map((k) => k.teks),
    ...(params.kegiatanPembelajaran?.akhir || []).map((k) => k.teks),
  ]
    .filter(Boolean)
    .slice(0, 5)
    .join('; ') || '-';

  const prompt = `
Anda adalah pakar penyusun Rencana Pemelajaran (RPM) Kurikulum SIUBA (Kurikulum Merdeka Terpadu & Berkarakter).
Tugas Anda: Buatlah Rincian Paragraf Trisula Kompetensi (TEPAT 1 PARAGRAF UTUH TERDIRI DARI ±2–4 KALIMAT UNTUK MASING-MASING DARI 3 PILAR) berdasarkan konteks pembelajaran berikut:

- Mata Pelajaran: ${params.mataPelajaran}
- Tingkat / Fase: ${params.tingkatFase || '-'} (${params.kelasRombel || '-'})
- Topik / Modul: ${params.modulTopik}
- Tujuan Pembelajaran (TP):
${tpListStr}
- Rincian Kegiatan: ${kegiatanStr}
- Alokasi Waktu: ${params.alokasiWaktu || 70} Menit

ATURAN DAN PANDUAN PEDAGOGIS (WAJIB DIPATUHI SANGAT KETAT):
1. Format Output: JSON murni TANPA markdown wrapper (\`\`\`json).
2. Tepat 3 field: "literasi", "numerasi", dan "diniyyah".
3. Masing-masing field HARUS berupa TEPAT 1 PARAGRAF UTUH (±2–4 kalimat). BUKAN daftar poin/bullet list, dan BUKAN esai panjang.
4. "literasi": Terkait langsung dengan topik "${params.modulTopik}". Jelaskan aktivitas santri dalam membaca teks rujukan, memahami konsep kunci, menganalisis informasi, atau menyajikan gagasan secara kritis dan komunikatif.
5. "numerasi": HARUS relevan dengan materi "${params.modulTopik}":
   - Jika mata pelajaran berhitung/kuantitatif (Matematika, IPA/Fisika/Kimia, dsb): sertakan pengolahan data numerik, estimasi, pengukuran, perbandingan nilai, atau interpretasi grafik/tabel yang masuk akal.
   - Jika mata pelajaran non-kuantitatif (Bahasa, Agama, Seni, IPS, dsb): JANGAN membuat hitungan palsu. Fokuskan numerasi pada penalaran logis, klasifikasi/pengelompokan data, perbandingan kronologis/pola, atau penafsiran tabel perbandingan sederhana.
6. "diniyyah" (Diniyyah & Adab): Integrasikan nilai adab dan akhlak Islam ke dalam aktivitas nyata pembelajaran (misal: adab berdiskusi dengan santun, mendengarkan teman, kejujuran pencatatan, ketelitian kerja, amanah, dan rasa syukur atas ilmu), BUKAN berupa khotbah moral terpisah yang abstrak.
7. Bahasa: Gunakan Bahasa Indonesia formal, komunikatif, dan siap pakai oleh guru (teacher-ready).

Kembalikan respon DALAM FORMAT JSON STRUKTUR BERIKUT:
{
  "literasi": "1 paragraf utuh (2-4 kalimat) kegiatan literasi kontekstual materi ${params.modulTopik}...",
  "numerasi": "1 paragraf utuh (2-4 kalimat) kegiatan numerasi kontekstual materi ${params.modulTopik}...",
  "diniyyah": "1 paragraf utuh (2-4 kalimat) integrasi adab dan nilai Islam dalam kegiatan materi ${params.modulTopik}..."
}
  `.trim();

  const maxRetries = 2;
  let attempt = 0;
  let lastFallbackReason: AIFallbackReason = 'UNKNOWN';

  while (attempt < maxRetries) {
    attempt++;
    const reqStartedAt = new Date();
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 30000);

    try {
      const response = await fetch(endpointUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        signal: controller.signal,
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
        }),
      });

      clearTimeout(timeoutId);
      const durationMs = Date.now() - reqStartedAt.getTime();

      if (response.status === 429) {
        const rawErrText = await response.text().catch(() => '');
        const classified = classifyProvider429(response.status, rawErrText);
        lastFallbackReason = classified;

        await recordAIUsageAttempt({
          userId: params.userId,
          feature: 'RPM_TRISULA',
          model,
          source: 'FALLBACK',
          providerHttpStatus: 429,
          providerErrorReason: classified,
          durationMs,
          retryAttempt: attempt,
          requestStartedAt: reqStartedAt,
        });

        if (classified === 'DAILY_QUOTA') {
          return getFallbackTrisulaParagraphs(params, 'DAILY_QUOTA', usageCheck.snapshot);
        }

        if (attempt < maxRetries) {
          const backoffDelay = Math.pow(2, attempt) * 1000 + Math.random() * 500;
          await new Promise((resolve) => setTimeout(resolve, backoffDelay));
          continue;
        }
        return getFallbackTrisulaParagraphs(params, 'RATE_LIMIT', usageCheck.snapshot);
      }

      if (response.status >= 500 || !response.ok) {
        lastFallbackReason = 'HTTP_ERROR';
        await recordAIUsageAttempt({
          userId: params.userId,
          feature: 'RPM_TRISULA',
          model,
          source: 'FALLBACK',
          providerHttpStatus: response.status,
          providerErrorReason: 'HTTP_ERROR',
          durationMs,
          retryAttempt: attempt,
          requestStartedAt: reqStartedAt,
        });

        if (attempt < maxRetries) {
          const backoffDelay = Math.pow(2, attempt) * 1000;
          await new Promise((resolve) => setTimeout(resolve, backoffDelay));
          continue;
        }
        return getFallbackTrisulaParagraphs(params, 'HTTP_ERROR', usageCheck.snapshot);
      }

      const data = await response.json();
      const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
      const cleanedText = rawText.replace(/```json/gi, '').replace(/```/g, '').trim();
      let parsed: any;

      try {
        parsed = JSON.parse(cleanedText);
      } catch {
        await recordAIUsageAttempt({
          userId: params.userId,
          feature: 'RPM_TRISULA',
          model,
          source: 'FALLBACK',
          providerHttpStatus: 200,
          providerErrorReason: 'INVALID_JSON',
          durationMs,
          retryAttempt: attempt,
          requestStartedAt: reqStartedAt,
        });
        return getFallbackTrisulaParagraphs(params, 'INVALID_JSON', usageCheck.snapshot);
      }

      const literasi = typeof parsed.literasi === 'string' ? parsed.literasi.trim() : '';
      const numerasi = typeof parsed.numerasi === 'string' ? parsed.numerasi.trim() : '';
      const diniyyah = typeof parsed.diniyyah === 'string'
        ? parsed.diniyyah.trim()
        : typeof parsed.diniyyahAdab === 'string'
        ? parsed.diniyyahAdab.trim()
        : '';

      if (!literasi || !numerasi || !diniyyah) {
        await recordAIUsageAttempt({
          userId: params.userId,
          feature: 'RPM_TRISULA',
          model,
          source: 'FALLBACK',
          providerHttpStatus: 200,
          providerErrorReason: 'INVALID_SCHEMA',
          durationMs,
          retryAttempt: attempt,
          requestStartedAt: reqStartedAt,
        });
        return getFallbackTrisulaParagraphs(params, 'INVALID_SCHEMA', usageCheck.snapshot);
      }

      await recordAIUsageAttempt({
        userId: params.userId,
        feature: 'RPM_TRISULA',
        model,
        source: 'GEMINI',
        providerHttpStatus: 200,
        durationMs,
        retryAttempt: attempt,
        requestStartedAt: reqStartedAt,
      });

      return {
        source: 'GEMINI',
        data: {
          literasi,
          numerasi,
          diniyyah,
        },
        usage: usageCheck.snapshot,
      };
    } catch (err: any) {
      clearTimeout(timeoutId);
      lastFallbackReason = controller.signal.aborted ? 'TIMEOUT' : 'NETWORK_ERROR';
      const durationMs = Date.now() - reqStartedAt.getTime();

      await recordAIUsageAttempt({
        userId: params.userId,
        feature: 'RPM_TRISULA',
        model,
        source: 'FALLBACK',
        providerErrorReason: lastFallbackReason,
        durationMs,
        retryAttempt: attempt,
        requestStartedAt: reqStartedAt,
      });

      if (attempt >= maxRetries) {
        return getFallbackTrisulaParagraphs(params, lastFallbackReason, usageCheck.snapshot);
      }
      const backoffDelay = Math.pow(2, attempt) * 1000;
      await new Promise((resolve) => setTimeout(resolve, backoffDelay));
    }
  }

  return getFallbackTrisulaParagraphs(params, lastFallbackReason, usageCheck.snapshot);
}
